name = input('Digite seu nome: ')
print(f'É um prazer te conhecer, {name:20}!')
print(f'É um prazer te conhecer, {name:>20}!')
print(f'É um prazer te conhecer, {name:<20}!')
print(f'É um prazer te conhecer, {name:^20}!')
print(f'É um prazer te conhecer, {name:=^20}!')
